In [27]:
import numpy as np
import pandas as pd

dados = pd.read_csv('../../data/heart_disease.csv') 

dados.head()
dados.shape

(253680, 22)

In [28]:
# fazer uma copia do dataset, para trabalhar sem riscos
dados2 = pd.DataFrame.copy(dados)

In [29]:
dados2.head()

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0

In [30]:
dados2.dtypes

HeartDiseaseorAttack    float64
HighBP                  float64
HighChol                float64
CholCheck               float64
BMI                     float64
Smoker                  float64
Stroke                  float64
Diabetes                float64
PhysActivity            float64
Fruits                  float64
Veggies                 float64
HvyAlcoholConsump       float64
AnyHealthcare           float64
NoDocbcCost             float64
GenHlth                 float64
MentHlth                float64
PhysHlth                float64
DiffWalk                float64
Sex                     float64
Age                     float64
Education               float64
Income                  float64
dtype: object

In [31]:
# Selecioanr colunas relevantes para classificação
previsores = dados2.iloc[:, 1:].values

In [32]:
previsores

array([[1., 1., 1., ..., 9., 4., 3.],
       [0., 0., 0., ..., 7., 6., 1.],
       [1., 1., 1., ..., 9., 4., 8.],
       ...,
       [0., 0., 1., ..., 2., 5., 2.],
       [1., 0., 1., ..., 7., 5., 1.],
       [1., 1., 1., ..., 9., 6., 2.]])

In [33]:
#meu alvo == target
alvo = dados2.iloc[:, 0].values

In [34]:
alvo

array([0., 0., 0., ..., 0., 0., 1.])

In [35]:
dados2.describe()

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
count,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,...,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000
mean,0.094186,0.429001,0.424121,0.962670,28.382364,0.443169,0.040571,0.296921,0.756544,0.634256,...,0.951053,0.084177,2.511392,3.184772,4.242081,0.168224,0.440342,8.032119,5.050434,6.053875
std,0.292087,0.494934,0.494210,0.189571,6.608694,0.496761,0.197294,0.698160,0.429169,0.481639,...,0.215759,0.277654,1.068477,7.412847,8.717951,0.374066,0.496429,3.054220,0.985774,2.071148
min,0.000000,0.000000,0.000000,0.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000
25%,0.000000,0.000000,0.000000,1.000000,24.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,6.000000,4.000000,5.000000
50%,0.000000,0.000000,0.000000,1.000000,27.000000,0.000000,0.000000,0.000000,1.000000,1.000000,...,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,8.000000,5.000000,7.000000
75%,0.000000,1.000000,1.000000,1.000000,31.000000,1.000000,0.000000,0.000000,1.000000,1.000000,...,1.000000,0.000000,3.000000,2.000000,3.000000,0.000000,1.000000,10.000000,6.000000,8.000000
max,1.000000,1.000000,1.000000,1.000000,98.000000,1.000000,1.000000,2.000000,1.000000,1.000000,...,1.000000,1.000000,5.000000,30.000000,30.000000,1.000000,1.000000,13.000000,6.000000,8.000000

In [36]:
from sklearn.preprocessing import StandardScaler # padronização

In [37]:
# vai transformar previsores com relação a sua scscala
previsores_esc = StandardScaler().fit_transform(previsores)

In [38]:
previsores_esc

array([[ 1.15368814,  1.16525449,  0.19692156, ...,  0.31690008,
        -1.06559465, -1.4744874 ],
       [-0.86678537, -0.85818163, -5.07816412, ..., -0.33793279,
         0.96327159, -2.44013754],
       [ 1.15368814,  1.16525449,  0.19692156, ...,  0.31690008,
        -1.06559465,  0.93963796],
       ...,
       [-0.86678537, -0.85818163,  0.19692156, ..., -1.97501498,
        -0.05116153, -1.95731247],
       [ 1.15368814, -0.85818163,  0.19692156, ..., -0.33793279,
        -0.05116153, -2.44013754],
       [ 1.15368814,  1.16525449,  0.19692156, ...,  0.31690008,
         0.96327159, -1.95731247]])

In [39]:
dados3 = pd.DataFrame(previsores_esc)
dados3

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,1.153688,1.165254,0.196922,1.757936,1.120927,-0.205637,-0.425292,-1.762814,-1.316872,0.482087,...,0.226863,-0.303173,2.329121,1.998592,1.233999,2.223615,-0.887021,0.316900,-1.065595,-1.474487
1,-0.866785,-0.858182,-5.078164,-0.511806,1.120927,-0.205637,-0.425292,0.567275,-1.316872,-2.074316,...,-4.407954,3.298445,0.457294,-0.429630,-0.486592,-0.449718,-0.887021,-0.337933,0.963272,-2.440138
2,1.153688,1.165254,0.196922,-0.057858,-0.892119,-0.205637,-0.425292,-1.762814,0.759375,-2.074316,...,0.226863,3.298445,2.329121,3.617407,2.954590,2.223615,-0.887021,0.316900,-1.065595,0.939638
3,1.153688,-0.858182,0.196922,-0.209174,-0.892119,-0.205637,-0.425292,0.567275,0.759375,0.482087,...,0.226863,-0.303173,-0.478619,-0.429630,-0.486592,-0.449718,-0.887021,0.971733,-2.080028,-0.026012
4,1.153688,1.165254,0.196922,-0.663122,-0.892119,-0.205637,-0.425292,0.567275,0.759375,0.482087,...,0.226863,-0.303173,-0.478619,-0.024926,-0.486592,-0.449718,-0.887021,0.971733,-0.051162,-0.991662
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,1.153688,1.165254,0.196922,2.514516,-0.892119,-0.205637,-0.425292,-1.762814,0.759375,0.482087,...,0.226863,-0.303173,0.457294,-0.429630,0.086938,-0.449718,1.127369,-0.992766,0.963272,0.456813
253676,1.153688,1.165254,0.196922,-1.571019,-0.892119,-0.205637,2.439387,-1.762814,-1.316872,-2.074316,...,0.226863,-0.303173,1.393207,-0.429630,-0.486592,2.223615,-0.887021,0.971733,-3.094461,-0.991662
253677,-0.866785,-0.858182,0.196922,-0.057858,-0.892119,-0.205637,-0.425292,0.567275,0.759375,-2.074316,...,0.226863,-0.303173,-1.414532,-0.429630,-0.486592,-0.449718,-0.887021,-1.975015,-0.051162,-1.957312
253678,1.153688,-0.858182,0.196922,-0.814438,-0.892119,-0.205637,-0.425292,-1.762814,0.759375,0.482087,...,0.226863,-0.303173,0.457294,-0.429630,-0.486592,-0.449718,1.127369,-0.337933,-0.051162,-2.440138
253679,1.153688,1.165254,0.196922,-0.511806,-0.892119,-0.205637,2.439387,0.567275,0.759375,-2.074316,...,0.226863,-0.303173,-0.478619,-0.429630,-0.486592,-0.449718,-0.887021,0.316900,0.963272,-1.957312

In [40]:
dados3.describe()

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
count,2.536800e+05,2.536800e+05,2.536800e+05,2.536800e+05,2.536800e+05,2.536800e+05,2.536800e+05,2.536800e+05,2.536800e+05,2.536800e+05,...,2.536800e+05,2.536800e+05,2.536800e+05,2.536800e+05,2.536800e+05,2.536800e+05,2.536800e+05,2.536800e+05,2.536800e+05,2.536800e+05
mean,-1.250340e-16,5.769939e-17,1.245859e-16,-2.505162e-16,2.688903e-17,-4.033355e-18,-1.254822e-17,5.377807e-17,5.601882e-17,-2.487236e-17,...,4.481506e-17,-1.792602e-17,1.711935e-16,8.963011e-18,3.450759e-17,2.554458e-17,1.299637e-16,6.767074e-17,-8.514861e-17,7.170409e-17
std,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,...,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00
min,-8.667854e-01,-8.581816e-01,-5.078164e+00,-2.478916e+00,-8.921186e-01,-2.056365e-01,-4.252922e-01,-1.762814e+00,-1.316872e+00,-2.074316e+00,...,-4.407954e+00,-3.031731e-01,-1.414532e+00,-4.296296e-01,-4.865924e-01,-4.497181e-01,-8.870209e-01,-2.302431e+00,-4.108894e+00,-2.440138e+00
25%,-8.667854e-01,-8.581816e-01,1.969216e-01,-6.631223e-01,-8.921186e-01,-2.056365e-01,-4.252922e-01,5.672748e-01,-1.316872e+00,4.820866e-01,...,2.268626e-01,-3.031731e-01,-4.786188e-01,-4.296296e-01,-4.865924e-01,-4.497181e-01,-8.870209e-01,-6.653492e-01,-1.065595e+00,-5.088373e-01
50%,-8.667854e-01,-8.581816e-01,1.969216e-01,-2.091739e-01,-8.921186e-01,-2.056365e-01,-4.252922e-01,5.672748e-01,7.593754e-01,4.820866e-01,...,2.268626e-01,-3.031731e-01,-4.786188e-01,-4.296296e-01,-4.865924e-01,-4.497181e-01,-8.870209e-01,-1.051636e-02,-5.116153e-02,4.568129e-01
75%,1.153688e+00,1.165254e+00,1.969216e-01,3.960906e-01,1.120927e+00,-2.056365e-01,-4.252922e-01,5.672748e-01,7.593754e-01,4.820866e-01,...,2.268626e-01,-3.031731e-01,4.572943e-01,-1.598272e-01,-1.424742e-01,-4.497181e-01,1.127369e+00,6.443165e-01,9.632716e-01,9.396380e-01
max,1.153688e+00,1.165254e+00,1.969216e-01,1.053427e+01,1.120927e+00,4.862949e+00,2.439387e+00,5.672748e-01,7.593754e-01,4.820866e-01,...,2.268626e-01,3.298445e+00,2.329121e+00,3.617407e+00,2.954590e+00,2.223615e+00,1.127369e+00,1.626566e+00,9.632716e-01,9.396380e-01

In [41]:
# transformar com labelEncoder
from sklearn.preprocessing import LabelEncoder

In [42]:
dados.head()

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0

In [43]:
previsores2 = dados2.iloc[:, 1:].values  
previsores2

array([[1., 1., 1., ..., 9., 4., 3.],
       [0., 0., 0., ..., 7., 6., 1.],
       [1., 1., 1., ..., 9., 4., 8.],
       ...,
       [0., 0., 1., ..., 2., 5., 2.],
       [1., 0., 1., ..., 7., 5., 1.],
       [1., 1., 1., ..., 9., 6., 2.]])

In [44]:
# OneHotEnconcer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [45]:
ColumnTransformer

sklearn.compose._column_transformer.ColumnTransformer

In [46]:
previsores2 = pd.DataFrame(previsores2)
previsores2.head()

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0

In [47]:
# vai transformar previsores com relação a sua scscala
previsores2_esc = StandardScaler().fit_transform(previsores2)

In [48]:
previsores2_esc

array([[ 1.15368814,  1.16525449,  0.19692156, ...,  0.31690008,
        -1.06559465, -1.4744874 ],
       [-0.86678537, -0.85818163, -5.07816412, ..., -0.33793279,
         0.96327159, -2.44013754],
       [ 1.15368814,  1.16525449,  0.19692156, ...,  0.31690008,
        -1.06559465,  0.93963796],
       ...,
       [-0.86678537, -0.85818163,  0.19692156, ..., -1.97501498,
        -0.05116153, -1.95731247],
       [ 1.15368814, -0.85818163,  0.19692156, ..., -0.33793279,
        -0.05116153, -2.44013754],
       [ 1.15368814,  1.16525449,  0.19692156, ...,  0.31690008,
         0.96327159, -1.95731247]])

In [49]:
dados4 = pd.DataFrame(previsores2_esc)
dados4

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,1.153688,1.165254,0.196922,1.757936,1.120927,-0.205637,-0.425292,-1.762814,-1.316872,0.482087,...,0.226863,-0.303173,2.329121,1.998592,1.233999,2.223615,-0.887021,0.316900,-1.065595,-1.474487
1,-0.866785,-0.858182,-5.078164,-0.511806,1.120927,-0.205637,-0.425292,0.567275,-1.316872,-2.074316,...,-4.407954,3.298445,0.457294,-0.429630,-0.486592,-0.449718,-0.887021,-0.337933,0.963272,-2.440138
2,1.153688,1.165254,0.196922,-0.057858,-0.892119,-0.205637,-0.425292,-1.762814,0.759375,-2.074316,...,0.226863,3.298445,2.329121,3.617407,2.954590,2.223615,-0.887021,0.316900,-1.065595,0.939638
3,1.153688,-0.858182,0.196922,-0.209174,-0.892119,-0.205637,-0.425292,0.567275,0.759375,0.482087,...,0.226863,-0.303173,-0.478619,-0.429630,-0.486592,-0.449718,-0.887021,0.971733,-2.080028,-0.026012
4,1.153688,1.165254,0.196922,-0.663122,-0.892119,-0.205637,-0.425292,0.567275,0.759375,0.482087,...,0.226863,-0.303173,-0.478619,-0.024926,-0.486592,-0.449718,-0.887021,0.971733,-0.051162,-0.991662
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,1.153688,1.165254,0.196922,2.514516,-0.892119,-0.205637,-0.425292,-1.762814,0.759375,0.482087,...,0.226863,-0.303173,0.457294,-0.429630,0.086938,-0.449718,1.127369,-0.992766,0.963272,0.456813
253676,1.153688,1.165254,0.196922,-1.571019,-0.892119,-0.205637,2.439387,-1.762814,-1.316872,-2.074316,...,0.226863,-0.303173,1.393207,-0.429630,-0.486592,2.223615,-0.887021,0.971733,-3.094461,-0.991662
253677,-0.866785,-0.858182,0.196922,-0.057858,-0.892119,-0.205637,-0.425292,0.567275,0.759375,-2.074316,...,0.226863,-0.303173,-1.414532,-0.429630,-0.486592,-0.449718,-0.887021,-1.975015,-0.051162,-1.957312
253678,1.153688,-0.858182,0.196922,-0.814438,-0.892119,-0.205637,-0.425292,-1.762814,0.759375,0.482087,...,0.226863,-0.303173,0.457294,-0.429630,-0.486592,-0.449718,1.127369,-0.337933,-0.051162,-2.440138
253679,1.153688,1.165254,0.196922,-0.511806,-0.892119,-0.205637,2.439387,0.567275,0.759375,-2.074316,...,0.226863,-0.303173,-0.478619,-0.429630,-0.486592,-0.449718,-0.887021,0.316900,0.963272,-1.957312

In [50]:
dados4.describe()

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
count,2.536800e+05,2.536800e+05,2.536800e+05,2.536800e+05,2.536800e+05,2.536800e+05,2.536800e+05,2.536800e+05,2.536800e+05,2.536800e+05,...,2.536800e+05,2.536800e+05,2.536800e+05,2.536800e+05,2.536800e+05,2.536800e+05,2.536800e+05,2.536800e+05,2.536800e+05,2.536800e+05
mean,-1.250340e-16,5.769939e-17,1.245859e-16,-2.505162e-16,2.688903e-17,-4.033355e-18,-1.254822e-17,5.377807e-17,5.601882e-17,-2.487236e-17,...,4.481506e-17,-1.792602e-17,1.711935e-16,8.963011e-18,3.450759e-17,2.554458e-17,1.299637e-16,6.767074e-17,-8.514861e-17,7.170409e-17
std,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,...,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00,1.000002e+00
min,-8.667854e-01,-8.581816e-01,-5.078164e+00,-2.478916e+00,-8.921186e-01,-2.056365e-01,-4.252922e-01,-1.762814e+00,-1.316872e+00,-2.074316e+00,...,-4.407954e+00,-3.031731e-01,-1.414532e+00,-4.296296e-01,-4.865924e-01,-4.497181e-01,-8.870209e-01,-2.302431e+00,-4.108894e+00,-2.440138e+00
25%,-8.667854e-01,-8.581816e-01,1.969216e-01,-6.631223e-01,-8.921186e-01,-2.056365e-01,-4.252922e-01,5.672748e-01,-1.316872e+00,4.820866e-01,...,2.268626e-01,-3.031731e-01,-4.786188e-01,-4.296296e-01,-4.865924e-01,-4.497181e-01,-8.870209e-01,-6.653492e-01,-1.065595e+00,-5.088373e-01
50%,-8.667854e-01,-8.581816e-01,1.969216e-01,-2.091739e-01,-8.921186e-01,-2.056365e-01,-4.252922e-01,5.672748e-01,7.593754e-01,4.820866e-01,...,2.268626e-01,-3.031731e-01,-4.786188e-01,-4.296296e-01,-4.865924e-01,-4.497181e-01,-8.870209e-01,-1.051636e-02,-5.116153e-02,4.568129e-01
75%,1.153688e+00,1.165254e+00,1.969216e-01,3.960906e-01,1.120927e+00,-2.056365e-01,-4.252922e-01,5.672748e-01,7.593754e-01,4.820866e-01,...,2.268626e-01,-3.031731e-01,4.572943e-01,-1.598272e-01,-1.424742e-01,-4.497181e-01,1.127369e+00,6.443165e-01,9.632716e-01,9.396380e-01
max,1.153688e+00,1.165254e+00,1.969216e-01,1.053427e+01,1.120927e+00,4.862949e+00,2.439387e+00,5.672748e-01,7.593754e-01,4.820866e-01,...,2.268626e-01,3.298445e+00,2.329121e+00,3.617407e+00,2.954590e+00,2.223615e+00,1.127369e+00,1.626566e+00,9.632716e-01,9.396380e-01

### Salvando

In [51]:
import pickle

In [52]:
# criar arquivo e depois atribuir var. a ele
arq1 = open('heart.pkl', 'wb')
pickle.dump(alvo,arq1)
arq2 = open('heart.pkl', 'wb')
pickle.dump(previsores,arq2)
arq3 = open('heart.pkl', 'wb')
pickle.dump(previsores_esc,arq3)
arq4 = open('heart.pkl', 'wb')
pickle.dump(previsores2,arq4)
arq5 = open('heart.pkl', 'wb')
pickle.dump(previsores2_esc,arq5)

In [53]:
# ler arquivo
arq5 = open('heart.pkl', 'rb')
# executar 
x = pickle.load(arq5)# previsores2_esc
x

array([[ 1.15368814,  1.16525449,  0.19692156, ...,  0.31690008,
        -1.06559465, -1.4744874 ],
       [-0.86678537, -0.85818163, -5.07816412, ..., -0.33793279,
         0.96327159, -2.44013754],
       [ 1.15368814,  1.16525449,  0.19692156, ...,  0.31690008,
        -1.06559465,  0.93963796],
       ...,
       [-0.86678537, -0.85818163,  0.19692156, ..., -1.97501498,
        -0.05116153, -1.95731247],
       [ 1.15368814, -0.85818163,  0.19692156, ..., -0.33793279,
        -0.05116153, -2.44013754],
       [ 1.15368814,  1.16525449,  0.19692156, ...,  0.31690008,
         0.96327159, -1.95731247]])